name: Lint Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "^3.10"

      - name: Install Poetry
        run: |
          pip install poetry==1.8.5

      - name: Install dependencies
        run: |
          poetry install

      - name: Run flake8 (Linting)
        run: poetry run flake8 . 

      - name: Run black (Code formatting check)
        run: poetry run black --check .  
        
      - name: Run isort (Imports sorting check)
        run: poetry run isort --check-only . 
