name: Release Python Package and GitHub Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write
  id-token: write  # Needed for PyPI publishing

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "^3.10"

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Build release distributions
        run: |
          poetry build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          password: ${{ secrets.PYPI_TOKEN }}

  github-release:
    runs-on: ubuntu-latest
    needs:
      - release-build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version from Git tag
        id: extract-version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ env.VERSION }}
          body: |
            **Release Notes**
            - Kavacham version ${{ env.VERSION }} published to PyPI.
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
